version: "3.8"

volumes:
  ab_postgres:
  ab_redis:

services:
  postgres:
    image: postgres:12.7
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      # - POSTGRES_INITDB_ARGS="--locale=ko_KR.UTF-8" (locale setting error)
    ports:
      - 9001:5432
    volumes:
      - ab_postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.8
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 9002:5462

  redis:
    depends_on:
      - rabbitmq
    image: redis:6.2.2
    ports:
      - 9003:6379
    volumes:
      - ab_redis:/data

  django:
    depends_on:
      - postgres
      - redis
    build:
      context: . # repo dir
      dockerfile: ./compose/dev.Dockerfile
    env_file: ./servers/development/.env.development
    volumes:
      - .:/app
    command:
      - /bin/bash
      - -c
      - |
        sh compose/wait-for/wait-for-postgres.sh postgres
        cd homebooks
        python manage.py runserver 0:8000

      # dockerize -wait tcp://postgres:5432 -timeout 15s
      # dockerize -wait tcp://redis:6379 -timeout 15s
      # python manage.py runserver 0:8000

