version: "3.8"

volumes:
  ab_postgres_vol: {}
  ab_redis_vol: {}

services:
  alpha_django:
    depends_on:
      - bravo_postgres
      - charlie_redis
    build:
      context: ../../ # repo directory
      dockerfile: servers/development_server/django.dockerfile
    env_file: .env.development.django
    ports:
      - 8000:8000
    command:
      - /bin/sh
      - -c
      - |
        dockerize -wait tcp://bravo_postgres:5432 -timeout 10s
        dockerize -wait tcp://charlie_redis:6379 -timeout 15s
        python manage.py runserver 0:8000

  bravo_postgres:
    image: postgres:12.6
    env_file: .env.development.postgres
    ports:
      - 8001:5432
    volumes:
      - ab_postgres_vol:/var/lib/postgresql/data

  charlie_redis:
    image: redis:6.2.2
    ports:
      - 8002:6397
    volumes:
      - ab_redis_vol:/data
