version: "3.8"

volumes:
  ab_postgres_vol: {}
  ab_redis_vol: {}

services:
  bravo_postgres:
    image: postgres:12.6
    environment:
      - POSTGRES_USER=${SERVER_DEFAULT_DB_USERNAME}
      - POSTGRES_PASSWORD=${SERVER_DEFAULT_DB_PASSWORD}
      - POSTGRES_DB=${SERVER_DEFAULT_DB_DBNAME}
      # encoding options (UTF-8) will be default
    ports:
      - ${SERVER_DEFAULT_DB_EXPOSE_PORT}:${SERVER_DEFAULT_DB_PORT}
    volumes:
      - ab_postgres_vol:/var/lib/postgresql/data

  charlie_redis:
    image: redis:6.2.2
    ports:
      - ${SERVER_REDIS_PORT}:${SERVER_REDIS_EXPOSE_PORT}
    volumes:
      - ab_redis_vol:/data
