"""
Django settings for homebooks project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
# built-in
import os
from pathlib import Path

# pypi
from dotenv import load_dotenv

# module
from homebooks.settings.base import *

DEV_ENV = REPO_DIR / "servers" / "development" / ".env.development"
load_dotenv(DEV_ENV)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["SERVER_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # apps, 3rd party
    "debug_toolbar",
    "rest_framework",
    "corsheaders",
    "django_pydenticon",
    # apps, local
    "accounts",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# username:password@host:port/database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "USER": os.environ["SERVER_DEFAULT_DB_USERNAME"],
        "PASSWORD": os.environ["SERVER_DEFAULT_DB_PASSWORD"],
        "HOST": os.environ["SERVER_DEFAULT_DB_HOST"],
        "PORT": os.environ["SERVER_DEFAULT_DB_EXPOSE_PORT"],
        "NAME": os.environ["SERVER_DEFAULT_DB_DBNAME"],
    }
}
